# Generated by Django 4.1 on 2023-08-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0003_student_delete_student1"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(default=None, upload_to="image"),
        ),
    ]
