# Generated by Django 4.1 on 2023-08-11 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0005_alter_student_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="image",
        ),
    ]
