# Generated by Django 4.1 on 2023-08-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0006_remove_student_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(default=None, upload_to=""),
        ),
    ]
