# Generated by Django 4.1 on 2023-08-12 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0008_alter_student_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="clas",
            new_name="dept",
        ),
    ]
