# Generated by Django 4.1 on 2023-08-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0009_rename_clas_student_dept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="dept",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(upload_to="pics/"),
        ),
    ]
