# Generated by Django 4.1 on 2023-08-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0010_alter_student_dept_alter_student_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(default=None, upload_to="pics/"),
        ),
    ]
