# Generated by Django 4.1 on 2023-08-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0014_alter_student_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
