# Generated by Django 4.1 on 2023-08-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0016_alter_student_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
