# Generated by Django 4.1 on 2023-08-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0017_student_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="present",
            field=models.BooleanField(default=False),
        ),
    ]
