# Generated by Django 4.1 on 2023-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0018_student_present"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(upload_to="_/"),
        ),
    ]
