# Generated by Django 4.1 on 2023-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0019_alter_student_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="present",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
